name: DNS Audit GitHub Action
description: "GitHub action to audit all DNS requests made by a workflow file"
author: "Canadian Digital Service"

inputs:
  output-file:
    description: "File to output results to"
    required: false
  start-tcpdump:
    description: "Flag if it should start tcpdump"
    required: true
    default: "true"

runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"

branding:
  icon: "sunrise"
  color: "white"
