name: CI Docker DNS

on:
  pull_request:
    branches:
      - main

jobs:
  ci-docker-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Capture DNS traffic
        uses: ./

      - name: Run docker container
        uses: cds-snc/terraform-tools-setup@v1
