name: CI Docker DNS

on:
  pull_request:
    branches:
      - main

jobs:
  ci-docker-dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Capture DNS traffic
        uses: ./
        with:
          start-tcpdump: true

      - name: Run docker container
        uses: cds-snc/terraform-tools-setup@v1

      - name: Write DNS traffic to file
        uses: ./
        with:
          output-file: dns_traffic.json

      - name: cat dns_traffic.json
        run: cat dns_traffic.json
